name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Run Tests 🧪
      #   run: npm test
      - name: Deploy 🚀
        uses: akhileshns/heroku-deploy@v3.12.14 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "young-forest-20958"
          heroku_email: "bensampsondev@gmail.com"
          buildpack: "mars/create-react-app"
          stack: "heroku-20"
          # action should not succeed if app crashes
          healthcheck: "https://young-forest-20958.herokuapp.com/health"
